#185172181 A user should be able to update an item in their collection
atlp-rwanda/Team-furebo-E-commerce-fn pull request #22
Opened 2023-06-02 10:11 UTC by bstwagir

### What does this PR do?
This PR adds the update product functionality
### Description of Task to be completed
A user, in this case, a seller will be able to keep his inventory up to date according to their encumen. Items quantity, prices, availability, and so on would be adjustable.
### How should this be manually tested?
* Navigate to the login page and click and sign in, if confirmed the user is a seller they have an option of viewing their collection.
* From the collection a single product can be accessed, and all the properties of that particular product will be displayed and they will be able to update them via a button present on the page that calls a form.
* The form can be filled with new values and the not needed one will remain as is.
* Enter a new password and confirm it, make sure it complies with the validation terms, and Submit.
### What are the relevant pivotal tracker/Trello stories?
#185172181

2023-06-26 18:08 UTC, JulesNIYOMWUNGERI submitted a review, later dismissed

2023-06-27 08:26 UTC, Raphaela664 requested changes
**On the product update form:**
- I don't think there should be a file chooser since you can delete or add an image from the preview
- It would also be better for the expiry date to use a date chooser instead of text field make date validation easier ex : 7/49/2023  should give an error

2023-06-29 08:28 UTC, Raphaela664 approved these changes

2023-06-29 10:55 UTC, nshutip approved these changes

2023-06-29 12:08 UTC, merged