#185172187 A seller should be able to delete a specific product in his collection
atlp-rwanda/Team-furebo-E-commerce-fn pull request #29
Opened 2023-06-08 14:20 UTC by bstwagir

### What does this PR do?
This PR adds the delete product functionality
### Description of Task to be completed
A user, in this case, a seller will be able to delete a product they no longer want to see displayed in their collection. 
### How should this be manually tested?
* Navigate to the login page and sign in, if confirmed the user is a seller they have an option of viewing their collection.
* From the collection a single product can be accessed, via a 'delete button present on the page they will be able to delete the chosen product.
### What are the relevant pivotal tracker/Trello stories?
#185172187

2023-06-23 16:08 UTC, ruberwa approved these changes

2023-06-23 16:22 UTC, ruberwa requested changes
- [x] Functionalities are okay only a few small things to fix, but one thing which is affecting your task and can do the same to the entire work time it goes to develop, We are using SASS as a team why Tailwind? I think you can take care of it first!

2023-06-24 18:33 UTC, ruberwa submitted a review, later dismissed

2023-06-25 19:16 UTC, nshutip approved these changes

2023-06-26 05:33 UTC, Raphaela664 requested changes

2023-06-26 05:33 UTC, Raphaela664 commented on src/redux/actions/proDetails.js
Change the baseUrl to the deployed one

2023-06-26 07:37 UTC, bstwagir commented on src/redux/actions/proDetails.js
The deployed URLs have been reinstated.

2023-06-26 07:40 UTC, Raphaela664 approved these changes
Well done!

2023-06-26 09:21 UTC, Raphaela664 approved these changes

2023-06-26 09:55 UTC, JulesNIYOMWUNGERI approved these changes

2023-06-26 12:03 UTC, merged